name: vup_chat
description: "Messenger app for ATProto powered by S5"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bluesky: ^0.16.0
  bluesky_chat: ^0.3.0
  flutter_secure_storage: ^9.2.2
  did_plc: ^0.0.19
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  js: ^0.6.7
  package_info_plus: ^8.0.0
  s5: ^0.2.0
  hive: ^2.2.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  lib5: ^0.2.0
  drift_db_viewer: ^2.1.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - static/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "static/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "static/icon.png"
    background_color: "#0D0D0D"
    theme_color: "#00C261"
  windows:
    generate: true
    image_path: "static/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "static/icon.png"
