name: Build On Tag

# on:
#   release:
#     types: [created]
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-ubuntu:
    name: "Build web, android, & linux"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get

      # Build web
      - run: flutter build web

      # Build linux
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux
      # - name: Upload release assets
      #   uses: alexellis/upload-assets@0.4.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     asset_paths: '["./build/web/**", "./build/linux/x64/release/bundle/vup_chat"]'
# TODO: Add Windows build

# TODO: Add MacOS & iOS bilds
