name: Release and build on tag

on:
  push:
    tags:
      - v*

jobs:
  build-ubuntu:
    name: "Build web, android, & linux"
    runs-on: ubuntu-latest
    steps:
      # Set up repo and java
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      # And begin the flutter
      - name: Install dependencies
        run: flutter pub get

      # Build web
      - name: Build Web
        run: flutter build web --web-renderer html

      # Create a zip file for the web build
      - name: Create web build zip
        run: |
          sudo apt-get install -y zip
          zip -r vup-chat-web.zip build/web

      # Build linux
      - name: Build Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libnotify-dev
          flutter build linux
          cd build/linux/x64/release
          zip -r ../../../../vup-chat-linux.zip bundle/
          cd ../../../..

      # Bulid android SIGNED
      - name: 🔧 Build APK
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          base64 -d <<< $KEY_JKS > ./android/app/release-key.jks
          ./flutterw build apk --release -v
          mkdir -p ./outputs
          cp build/app/outputs/apk/release/*.apk ./outputs/

      # Create release
      - name: Create a release with the APK.
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Changelog time!
      - name: Generate Changelog
        uses: smichard/conventional_changelog@2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git User Info
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
          git push git push origin HEAD:main

      # Now upload those assets
      - name: Upload release assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./vup-chat-web.zip", "./outputs/*", "vup-chat-linux.zip"]'
# TODO: Add Windows build

# TODO: Add MacOS & iOS bilds
