name: Build On Release

on:
  release:
    types: [created]

jobs:
  build-ubuntu:
    name: "Build web, android, & linux"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get

      # Build web
      - name: Build Web
        run: flutter build web --web-renderer html

      # Create a zip file for the web build
      - name: Create web build zip
        run: |
          sudo apt-get install -y zip
          zip -r vup-chat-web.zip build/web

      # Build linux
      - name: Build Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libnotify-dev
          flutter build linux
      - name: Upload release assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./vup-chat-web.zip", "./build/linux/x64/release/bundle/vup_chat"]'
# TODO: Add Windows build

# TODO: Add MacOS & iOS bilds
